// Legal copy, carried over verbatim from the existing AUTOTRIZ site.
// The operating entity is Triz International Sdn. Bhd.
//
// Treat these strings as the client's words: reformat freely, but do not
// reword them without sign-off.

export type LegalBlock = ["h2" | "p" | "li", string];

export type LegalDoc = {
  title: string;
  description: string;
  effective: string;
  blocks: LegalBlock[];
};

export const privacy_policy: LegalDoc = {
  title: "Privacy Policy",
  description: "How Triz International Sdn. Bhd. collects, uses and protects personal information submitted through auto-triz.com.",
  effective: "30 December 2024",
  blocks: [
  ["p", "A Legal Disclaimer"],
  ["p", "Triz International Sdn. Bhd. (\"we,\" \"our,\" or \"us\") values your privacy and is committed to protecting your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website"],
  ["p", "https://www.auto-triz.com"],
  ["p", ", use our services, or interact with us."],
  ["h2", "1. Information We Collect"],
  ["p", "We may collect the following types of information:"],
  ["h2", "a. Personal Information"],
  ["p", "Name, email address, phone number, and mailing address provided when you fill out forms or contact us."],
  ["p", "Payment information when you make purchases or transactions."],
  ["h2", "b. Non-Personal Information"],
  ["p", "Browser type, IP address, device information, and operating system through cookies and similar technologies."],
  ["p", "Website usage data, including pages viewed and time spent on the site."],
  ["h2", "c. Sensitive Personal Data (GDPR Compliance)"],
  ["p", "We do not intentionally collect sensitive personal data, such as health information, political opinions, or biometric data."],
  ["h2", "2. How We Use Your Information"],
  ["p", "We use the collected information for the following purposes:"],
  ["p", "To provide, operate, and improve our services and website."],
  ["p", "To respond to inquiries, process transactions, and provide customer support."],
  ["p", "To send promotional communications, updates, and offers (with your consent)."],
  ["p", "To analyze website performance and user behavior for optimization."],
  ["p", "To comply with legal obligations and protect our rights."],
  ["h2", "3. Sharing Your Information"],
  ["p", "We may share your information in the following circumstances:"],
  ["p", "Service Providers: With third-party vendors who assist in operating our website, conducting business, or servicing you."],
  ["p", "Legal Compliance: When required to comply with applicable laws, regulations, or legal proceedings."],
  ["p", "Business Transfers: In the event of a merger, sale, or acquisition of our company."],
  ["p", "We will never sell your personal information unless explicitly permitted under applicable laws, including GDPR and CCPA."],
  ["h2", "4. GDPR Compliance"],
  ["p", "If you are a resident of the European Economic Area (EEA), the following rights apply:"],
  ["p", "Access: You can request a copy of the personal data we hold about you."],
  ["p", "Correction: You can request corrections to inaccurate or incomplete data."],
  ["p", "Deletion (\"Right to be Forgotten\"): You can request the deletion of your personal data under specific circumstances."],
  ["p", "Restriction: You can request a restriction on the processing of your data."],
  ["p", "Portability: You can request that we transfer your data to another service provider."],
  ["p", "Objection: You can object to the processing of your data for direct marketing purposes."],
  ["p", "\u200b\u200b"],
  ["p", "To exercise these rights, contact us at"],
  ["p", "sales@auto-triz.com"],
  ["h2", "5. CCPA Compliance"],
  ["p", "If you are a resident of California, the following rights apply:"],
  ["p", "Right to Know: You have the right to request information about the categories of data we collect and how we use it."],
  ["p", "Right to Delete: You can request that we delete your personal data, subject to certain exceptions."],
  ["p", "Right to Opt-Out: You can opt out of the sale of your personal data."],
  ["p", "Non-Discrimination: You will not be discriminated against for exercising your CCPA rights."],
  ["p", "\u200b\u200b\u200b\u200b\u200b"],
  ["p", "To exercise these rights, contact us at"],
  ["p", "sales@auto-triz.com"],
  ["p", "or call"],
  ["p", "+60156263898"],
  ["h2", "6. Cookies and Tracking Technologies"],
  ["p", "We use cookies and similar tracking technologies to enhance user experience and analyze website traffic. By continuing to use our site, you consent to our use of cookies."],
  ["p", "Types of Cookies Used:"],
  ["p", "Essential Cookies: Necessary for website functionality."],
  ["p", "Analytics Cookies: Track site usage and performance."],
  ["p", "Marketing Cookies: Used for personalized advertising."],
  ["p", "You can manage or disable cookies through your browser settings."],
  ["h2", "7. Data Security"],
  ["p", "We implement robust security measures to protect your personal information from unauthorized access, alteration, or disclosure. However, no online platform is completely secure, and we cannot guarantee absolute security."],
  ["h2", "8. Third-Party Links"],
  ["p", "Our website may include links to third-party websites. We are not responsible for the privacy practices or content of these external sites. Please review their privacy policies before sharing your information."],
  ["p", "We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Please review carefully the third-party\u2019s policies and practices and make sure you understand them before you engage in any transaction. Complaints, claims, concerns, or questions regarding third-party products should be directed to the third-party."],
  ["p", "\u200b9. Changes to This Privacy Policy"],
  ["p", "We may update this Privacy Policy periodically. Any changes will be reflected on this page with a revised \"Effective Date.\" Continued use of our website constitutes your acknowledgment of these changes."],
  ["h2", "10. Contact Information"],
  ["p", "Questions about the Privacy Policy should be sent to us at:"],
  ["p", "Triz International Sdn Bhd (202101038972) (1439272-P)"],
  ["p", "43, Jalan Bidara 2/5, Taman Bidara, 68100 Batu Caves, Selangor, Malaysia."],
  ["p", "Tel: +6011 5626 3898"],
  ["p", "Email: sales@auto-triz.com"],
  ],
};

export const terms: LegalDoc = {
  title: "Terms & Conditions",
  description: "The terms of service governing use of the AUTOTRIZ website and any purchase made through it.",
  effective: "30 December 2024",
  blocks: [
  ["h2", "OVERVIEW"],
  ["p", "This website is operated by Triz International Sdn Bhd. Throughout the site, the terms \u201cwe\u201d, \u201cus\u201d and \u201cour\u201d refer to AUTOTRIZ. We offers this website, including all information, tools and services available from this site to you, the user, conditioned upon your acceptance of all terms, conditions, policies and notices stated here."],
  ["p", "By visiting our site and/ or purchasing something from us, you engage in our \u201cService\u201d and agree to be bound by the following terms and conditions (\u201cTerms of Service\u201d, \u201cTerms\u201d), including those additional terms and conditions and policies referenced herein and/or available by hyperlink. These Terms of Service apply to all users of the site, including without limitation users who are browsers, vendors, customers, merchants, and/ or contributors of content."],
  ["p", "Please read these Terms of Service carefully before accessing or using our website. By accessing or using any part of the site, you agree to be bound by these Terms of Service. If you do not agree to all the terms and conditions of this agreement, then you may not access the website or use any services. If these Terms of Service are considered an offer, acceptance is expressly limited to these Terms of Service."],
  ["p", "Any new features or tools which are added to the current store shall also be subject to the Terms of Service. You can review the most current version of the Terms of Service at any time on this page. We reserve the right to update, change or replace any part of these Terms of Service by posting updates and/or changes to our website. It is your responsibility to check this page periodically for changes. Your continued use of or access to the website following the posting of any changes constitutes acceptance of those changes."],
  ["p", "Our store is hosted with Wix Store. They provide us with the online e-commerce platform that allows us to sell our products and services to you."],
  ["h2", "SECTION 1 \u2013 ONLINE STORE TERMS"],
  ["p", "By agreeing to these Terms of Service, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site."],
  ["p", "You may not use our products for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws)."],
  ["p", "You must not transmit any worms or viruses or any code of a destructive nature."],
  ["p", "A breach or violation of any of the Terms will result in an immediate termination of your Services."],
  ["h2", "SECTION 2 \u2013 GENERAL CONDITIONS"],
  ["p", "We reserve the right to refuse service to anyone for any reason at any time."],
  ["p", "You understand that your content (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit card information is always encrypted during transfer over networks."],
  ["p", "You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service or any contact on the website through which the service is provided, without express written permission by us."],
  ["p", "The headings used in this agreement are included for convenience only and will not limit or otherwise affect these Terms."],
  ["h2", "SECTION 3 \u2013 ACCURACY, COMPLETENESS AND TIMELINESS OF INFORMATION"],
  ["p", "We are not responsible if information made available on this site is not accurate, complete or current. The material on this site is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or more timely sources of information. Any reliance on the material on this site is at your own risk."],
  ["p", "This site may contain certain historical information. Historical information, necessarily, is not current and is provided for your reference only. We reserve the right to modify the contents of this site at any time, but we have no obligation to update any information on our site. You agree that it is your responsibility to monitor changes to our site."],
  ["h2", "SECTION 4 \u2013 MODIFICATIONS TO THE SERVICE AND PRICES"],
  ["p", "Prices for our products are subject to change without notice."],
  ["p", "We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice at any time."],
  ["p", "We shall not be liable to you or to any third-party for any modification, price change, suspension or discontinuance of the Service."],
  ["p", "SECTION 5 \u2013 PRODUCTS OR SERVICES (if applicable)"],
  ["p", "Certain products or services may be available exclusively online through the website. These products or services may have limited quantities and are subject to return or exchange only according to our"],
  ["p", "Return Policy"],
  ["p", "We have made every effort to display as accurately as possible the colors and images of our products that appear at the store. We cannot guarantee that your computer monitor\u2019s display of any color will be accurate."],
  ["p", "We reserve the right, but are not obligated, to limit the sales of our products or Services to any person, geographic region or jurisdiction. We may exercise this right on a case-by-case basis. We reserve the right to limit the quantities of any products or services that we offer. All descriptions of products or product pricing are subject to change at anytime without notice, at the sole discretion of us. We reserve the right to discontinue any product at any time. Any offer for any product or service made on this site is void where prohibited."],
  ["p", "We do not warrant that the quality of any products, services, information, or other material purchased or obtained by you will meet your expectations, or that any errors in the Service will be corrected."],
  ["h2", "SECTION 6 \u2013 ACCURACY OF BILLING AND ACCOUNT INFORMATION"],
  ["p", "We reserve the right to refuse any order you place with us. We may, in our sole discretion, limit or cancel quantities purchased per person, per household or per order. These restrictions may include orders placed by or under the same customer account, the same credit card, and/or orders that use the same billing and/or shipping address. In the event that we make a change to or cancel an order, we may attempt to notify you by contacting the e-mail and/or billing address/phone number provided at the time the order was made. We reserve the right to limit or prohibit orders that, in our sole judgment, appear to be placed by dealers, resellers or distributors."],
  ["p", "You agree to provide current, complete and accurate purchase and account information for all purchases made at our store. You agree to promptly update your account and other information, including your email address and credit card numbers and expiration dates, so that we can complete your transactions and contact you as needed."],
  ["p", "For more detail, please review our"],
  ["p", "Returns Policy"],
  ["h2", "SECTION 7 \u2013 OPTIONAL TOOLS"],
  ["p", "We may provide you with access to third-party tools over which we neither monitor nor have any control nor input."],
  ["p", "You acknowledge and agree that we provide access to such tools \u201das is\u201d and \u201cas available\u201d without any warranties, representations or conditions of any kind and without any endorsement. We shall have no liability whatsoever arising from or relating to your use of optional third-party tools."],
  ["p", "Any use by you of optional tools offered through the site is entirely at your own risk and discretion and you should ensure that you are familiar with and approve of the terms on which tools are provided by the relevant third-party provider(s)."],
  ["p", "We may also, in the future, offer new services and/or features through the website (including, the release of new tools and resources). Such new features and/or services shall also be subject to these Terms of Service."],
  ["h2", "SECTION 8 \u2013 THIRD-PARTY LINKS"],
  ["p", "Certain content, products and services available via our Service may include materials from third-parties."],
  ["p", "Third-party links on this site may direct you to third-party websites that are not affiliated with us. We are not responsible for examining or evaluating the content or accuracy and we do not warrant and will not have any liability or responsibility for any third-party materials or websites, or for any other materials, products, or services of third-parties."],
  ["p", "We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Please review carefully the third-party\u2019s policies and practices and make sure you understand them before you engage in any transaction. Complaints, claims, concerns, or questions regarding third-party products should be directed to the third-party."],
  ["h2", "SECTION 9 \u2013 USER COMMENTS, FEEDBACK AND OTHER SUBMISSIONS"],
  ["p", "If, at our request, you send certain specific submissions (for example contest entries) or without a request from us you send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, \u2018comments\u2019), you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any medium any comments that you forward to us. We are and shall be under no obligation (1) to maintain any comments in confidence; (2) to pay compensation for any comments; or (3) to respond to any comments."],
  ["p", "We may, but have no obligation to, monitor, edit or remove content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party\u2019s intellectual property or these Terms of Service."],
  ["p", "You agree that your comments will not violate any right of any third-party, including copyright, trademark, privacy, personality or other personal or proprietary right. You further agree that your comments will not contain libelous or otherwise unlawful, abusive or obscene material, or contain any computer virus or other malware that could in any way affect the operation of the Service or any related website. You may not use a false e-mail address, pretend to be someone other than yourself, or otherwise mislead us or third-parties as to the origin of any comments. You are solely responsible for any comments you make and their accuracy. We take no responsibility and assume no liability for any comments posted by you or any third-party."],
  ["h2", "SECTION 10 \u2013 PERSONAL INFORMATION"],
  ["p", "Your submission of personal information through the store is governed by our"],
  ["p", "Privacy Policy"],
  ["p", ". To view our Privacy Policy, please visit:"],
  ["p", "https://www.auto-triz.com/privacy-policy"],
  ["h2", "SECTION 11 \u2013 ERRORS, INACCURACIES AND OMISSIONS"],
  ["p", "Occasionally there may be information on our site or in the Service that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, product shipping charges, transit times and availability. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any information in the Service or on any related website is inaccurate at any time without prior notice (including after you have submitted your order)."],
  ["p", "We undertake no obligation to update, amend or clarify information in the Service or on any related website, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Service or on any related website, should be taken to indicate that all information in the Service or on any related website has been modified or updated."],
  ["h2", "SECTION 12 \u2013 PROHIBITED USES"],
  ["p", "In addition to other prohibitions as set forth in the Terms of Service, you are prohibited from using the site or its content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate your use of the Service or any related website for violating any of the prohibited uses."],
  ["h2", "SECTION 13 \u2013 DISCLAIMER OF WARRANTIES; LIMITATION OF LIABILITY"],
  ["p", "We do not guarantee, represent or warrant that your use of our service will be uninterrupted, timely, secure or error-free."],
  ["p", "We do not warrant that the results that may be obtained from the use of the service will be accurate or reliable."],
  ["p", "You agree that from time to time we may remove the service for indefinite periods of time or cancel the service at any time, without notice to you."],
  ["p", "You expressly agree that your use of, or inability to use, the service is at your sole risk. The service and all products and services delivered to you through the service are (except as expressly stated by us) provided \u2018as is\u2019 and \u2018as available\u2019 for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement."],
  ["p", "In no case shall AUTOTRIZ, our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of any of the service or any products procured using the service, or for any other claim related in any way to your use of the service or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the service or any content (or product) posted, transmitted, or otherwise made available via the service, even if advised of their possibility. Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the maximum extent permitted by law."],
  ["h2", "SECTION 14 \u2013 INDEMNIFICATION"],
  ["p", "You agree to indemnify, defend and hold harmless AUTOTRIZ and our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, including reasonable attorneys\u2019 fees, made by any third-party due to or arising out of your breach of these Terms of Service or the documents they incorporate by reference, or your violation of any law or the rights of a third-party."],
  ["h2", "SECTION 15 \u2013 SEVERABILITY"],
  ["p", "In the event that any provision of these Terms of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms of Service, such determination shall not affect the validity and enforceability of any other remaining provisions."],
  ["h2", "SECTION 16 \u2013 TERMINATION"],
  ["p", "The obligations and liabilities of the parties incurred prior to the termination date shall survive the termination of this agreement for all purposes."],
  ["p", "These Terms of Service are effective unless and until terminated by either you or us. You may terminate these Terms of Service at any time by notifying us that you no longer wish to use our Services, or when you cease using our site."],
  ["p", "If in our sole judgment you fail, or we suspect that you have failed, to comply with any term or provision of these Terms of Service, we also may terminate this agreement at any time without notice and you will remain liable for all amounts due up to and including the date of termination; and/or accordingly may deny you access to our Services (or any part thereof)."],
  ["h2", "SECTION 17 \u2013 ENTIRE AGREEMENT"],
  ["p", "The failure of us to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision."],
  ["p", "These Terms of Service and any policies or operating rules posted by us on this site or in respect to The Service constitutes the entire agreement and understanding between you and us and govern your use of the Service, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us (including, but not limited to, any prior versions of the Terms of Service)."],
  ["p", "Any ambiguities in the interpretation of these Terms of Service shall not be construed against the drafting party."],
  ["h2", "SECTION 18 \u2013 GOVERNING LAW"],
  ["p", "These Terms of Service and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with the laws of Malaysia"],
  ["h2", "SECTION 19 \u2013 CHANGES TO TERMS OF SERVICE"],
  ["p", "You can review the most current version of the Terms of Service at any time at this page."],
  ["p", "We reserve the right, at our sole discretion, to update, change or replace any part of these Terms of Service by posting updates and changes to our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service following the posting of any changes to these Terms of Service constitutes acceptance of those changes."],
  ["h2", "SECTION 20 \u2013 CONTACT INFORMATION"],
  ["p", "Questions about the Terms of Service should be sent to us at:"],
  ["p", "Triz International Sdn Bhd (202101038972) (1439272-P)"],
  ["p", "43, Jalan Bidara 2/5, Taman Bidara, 68100 Batu Caves, Selangor, Malaysia."],
  ["p", "Tel: +6011 5626 3898"],
  ["p", "Email: sales@auto-triz.com"],
  ],
};

export const return_refund_policy: LegalDoc = {
  title: "Return & Refund Policy",
  description: "Conditions under which AUTOTRIZ products may be returned and refunded.",
  effective: "30 December 2024",
  blocks: [
  ["p", "Return and Refund Policy"],
  ["h2", "OVERVIEW"],
  ["p", "Thank you for shopping at AUTOTRIZ. If, for any reason, you are not completely satisfied with a purchase, we invite you to review our policy on refunds and returns. The following terms are applicable for any products that you purchased with us."],
  ["h2", "INTERPRETATIONS"],
  ["p", "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural."],
  ["h2", "DEFINATIONS"],
  ["p", "For the purposes of this Return and Refund Policy:"],
  ["p", "Company (referred to as either \u201cthe Company\u201d, \u201cwe\u201d, \u201cus\u201d or \u201cour\u201d in this Agreement) refers to Triz International Sdn Bhd"],
  ["p", "Goods refer to the items offered for sale on the Service."],
  ["p", "Orders mean a request by you to purchase Goods from us."],
  ["p", "Service refers to the Website."],
  ["p", "Website refers to"],
  ["p", "http://www.auto-triz.com"],
  ["p", "You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable."],
  ["h2", "YOUR ORDER CANCELLATION RIGHTS"],
  ["p", "You are entitled to cancel your order within 7 days without giving any reason for doing so."],
  ["p", "The deadline for canceling an order is 7 days from the date on which you received the Goods or on which a third party you have appointed, who is not the carrier, takes possession of the product delivered."],
  ["p", "In order to exercise your right of cancellation, you must inform us of your decision by means of a clear statement. You can inform us of your decision by"],
  ["p", "email:"],
  ["p", "sales@auto-triz.com"],
  ["p", "We will reimburse you no later than 14 days from the day on which we receive the returned Goods. We will use the same means of payment as you used for the order, and you will not incur any fees for such reimbursement."],
  ["h2", "CONDITIONS FOR RETURNS"],
  ["p", "In order for the goods to be eligible for a return, please make sure that:"],
  ["p", "The goods were purchased in the last 7 days"],
  ["p", "The goods are in the original packaging and unopened condition."],
  ["p", "The following Goods cannot be returned:"],
  ["p", "The supply of goods made to your specifications or clearly personalized."],
  ["p", "The supply of goods which according to their nature are not suitable to be returned, deteriorate rapidly or where the date of expiry is over."],
  ["p", "The supply of goods which are not suitable for return due to health protection or hygiene reasons and were unsealed after delivery."],
  ["p", "The supply of goods which are, after delivery, according to their nature, inseparably mixed with other items."],
  ["p", "We reserve the right to refuse returns of any merchandise that does not meet the above return conditions in our sole discretion."],
  ["p", "Only regular priced goods may be refunded. Unfortunately, goods on sale cannot be refunded. This exclusion may not apply to you if it is not permitted by applicable law."],
  ["p", "The company will charge a return and restocking fee equal to up to 10% (ten percent) of the order value plus applicable taxes to cover the packing and handling charges that cannot be recovered otherwise."],
  ["h2", "RETURNING GOODS"],
  ["p", "You are responsible for the cost and risk of returning the goods to us. You should send the goods at the following address:"],
  ["p", "Triz International Sdn Bhd (202101038972) (1439272-P)"],
  ["p", "43, Jalan Bidara 2/5, Taman Bidara, 68100 Batu Caves, Selangor, Malaysia"],
  ["p", "Tel: +601156263898 Email: sales@auto-triz.com"],
  ["p", "We cannot be held responsible for goods damaged or lost in return shipment. Therefore, We recommend an insured and trackable mail service. We are unable to issue a refund without actual receipt of the goods or proof of received return delivery."],
  ["h2", "GIFTS"],
  ["p", "If the goods were marked as a gift when purchased and then shipped directly to you, You\u2019ll receive a gift credit for the value of your return. Once the returned product is received, a gift certificate or credit note will be mailed to You."],
  ["p", "If the goods weren\u2019t marked as a gift when purchased, or the gift giver had the order shipped to themselves to give it to you later, We will send the refund to the gift giver."],
  ["h2", "CONTACT INFORMATION"],
  ["p", "Questions about the Terms of Service should be sent to us at:"],
  ["p", "Triz International Sdn Bhd (202101038972) (1439272-P)"],
  ["p", "43, Jalan Bidara 2/5, Taman Bidara, 68100 Batu Caves, Selangor, Malaysia."],
  ["p", "Tel: +6011 5626 3898"],
  ["p", "Email: sales@auto-triz.com"],
  ],
};
